# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
files: ^python/
exclude: .*python/src/cucumber_messages/_messages\.py
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969 # frozen: v0.12.5
    hooks:
      - id: ruff-check
        files: "^python/"
        args: [--fix]
      - id: ruff-format
        files: "^python/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-certifi]
