name: Release Perl

on:
  push:
    branches: [release/*]

jobs:
  publish-cpan:
    name: Publish to CPAN
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cucumber/action-publish-cpan@v1.0.1
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: 'perl'
