name: Release Elixir hex package

on:
  push:
    branches: [release/*]

jobs:
  create-hex-release:
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/test-elixir.yml
      - uses: cucumber/action-publish-hex@v1.0.0
        with:
          hex-api-key: ${{ secrets.HEX_API_KEY }}
          working-directory: 'elixir'
