name: Test Java

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  test-java:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '16']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: java-test
          set: |
            *.contexts.schema-codegen=
            java-test.args.JAVA_VERSION=${{ matrix.java }}
            java-test.cache-to=type=gha,scope=java-test-${{ matrix.java }},mode=max
            java-test.cache-from=type=gha,scope=java-test-${{ matrix.java }}

  test-java-mac-windows:
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java: ["11", "17"]
        include:
          - os: windows-latest
            java: "17"
          - os: macos-latest
            java: "17"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - run: mvn install
        working-directory: java

      - run: mvn test
        working-directory: java
        
      - run: mvn clean package javadoc:jar -DskipTests=true
        working-directory: java
        
